name: Scala CI

on:
  workflow_dispatch:
  #  push:
  #  branches: [ main ]
  #  pull_request:
  #  branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11', '17', '18']
    name: Java ${{ matrix.java }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: 'sbt'
    - name: Run tests
      run: sbt test
    - name: Check code style with scalafmt
      run: sbt scalafmtCheckAll
    - name: Check code style with scalafix
      run: sbt "scalafixAll --check"
